<?php

namespace App\Constants;

class Hashtag
{
    public const STRONG_HASHTAGS = [
        '#standuppaddle',
        '#standuppaddleboard',
        '#standuppaddling',
        '#standuppaddleboarding',
        '#paddleboarding',
        '#paddleboardgear',
        '#suppaddle',
        '#suplife',
        '#supadventure',
        '#supboarding',
        '#supaddict',
        '#supfun',
        '#suparoundtheworld',
        '#suptravel',
        '#supdestinations',
        '#supandexplore',
        '#supgermany',
        '#supadventuretime',
        '#supnature',
        '#supsunset',
        '#supocean',
        '#supfitness',
        '#supyoga',
        '#supsurf',
        '#supsurfing',
        '#supsurfer',
        '#supschool',
        '#supracing',
        '#supfishing',
        '#supcamping',
        '#suphiking',
        '#suptouring',
        '#supgear',
        '#supboard',
        '#inflatablesup',
        '#isup',
        '#supaccessories',
        '#supfornature',
        '#supcommunity',
        '#supvibes',
        '#supaddiction',
        '#supfamily',
        '#wintersup',
        '#autumnsup',
        '#summersup',
        '#springsup',
        '#coldwatersup',
        '#supmoments',
        '#paddleadventure',
        '#supandsmile',
        '#supgoals',
        '#supalps',
        '#riversup',
        '#lakesup',
        '#beachsup',
        '#oceansup',
    ];

    public const WEAK_HASHTAGS = [
        '#sup',
    ];
}
